version: '3.8'
services:
  backend:
    build: ./backend
    container_name: cricket_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./frontend
    container_name: cricket_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app       # Mount the entire frontend directory
      - /app/node_modules      # Use a named volume for node_modules to preserve installed dependencies
    environment:
      - CHOKIDAR_USEPOLLING=true
